// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test} from "forge-std/Test.sol";
import {IUniswapV3Factory} from "v3-core/contracts/interfaces/IUniswapV3Factory.sol";
import {IUniswapV3Pool} from "v3-core/contracts/interfaces/IUniswapV3Pool.sol";
import {IUniswapV3MintCallback} from "v3-core/contracts/interfaces/callback/IUniswapV3MintCallback.sol";

import {PairVault} from "../src/PairVault.sol";
import {LiquidityMath} from "../src/libraries/LiquidityMath.sol";
import {TickMath} from "../src/libraries/TickMath.sol";
import {MockERC20, MockPyth} from "./PairVault.t.sol";
import {V3TestRouter} from "./utils/V3TestRouter.sol";

/// @notice Verifies PairVault.collectFees against REAL swap fees generated by
///         a real swap through a real Uniswap v3 pool — not a mock, and not a
///         zero-fee no-op. This is also the empirical check on the fee
///         accounting header's central claim (README "Fee accounting"):
///         with two distinct owners (an outside LP and the vault) holding
///         liquidity in the identical range, each accrues fees strictly
///         proportional to its own share — automatically, with nothing in
///         this test computing a split.
contract PairVaultFeesTest is Test {
    IUniswapV3Factory factory;
    IUniswapV3Pool pool;
    V3TestRouter router;
    MockERC20 token0;
    MockERC20 token1;
    MockPyth pyth;
    PairVault vault;

    bytes32 constant FEED0 = bytes32(uint256(20));
    bytes32 constant FEED1 = bytes32(uint256(21));
    address swapper = address(0x5A9);
    address treasury = address(0x7EA5);
    address keeper = address(0xCEE9E5);

    function setUp() public {
        factory = IUniswapV3Factory(vm.deployCode("UniswapV3Factory.sol"));
        router = new V3TestRouter();

        MockERC20 a = new MockERC20("A", 18);
        MockERC20 b = new MockERC20("B", 18);
        (token0, token1) = address(a) < address(b) ? (a, b) : (b, a);

        pyth = new MockPyth();
        pyth.setPrice(FEED0, 1e8, -8);
        pyth.setPrice(FEED1, 1e8, -8);

        pool = IUniswapV3Pool(factory.createPool(address(token0), address(token1), 3000)); // 0.3%
        pool.initialize(uint160(1) << 96);

        vault = new PairVault(
            address(token0), address(token1), 18, 18, FEED0, FEED1, address(pyth), address(pool), 1, address(this), treasury, address(0)
        );

        // Fund and open the vault's own band (via the real openBand path).
        token0.mint(address(0xD0), 10_000e18);
        token1.mint(address(0xD0), 10_000e18);
        vm.startPrank(address(0xD0));
        vault.deposit(address(token0), 10_000e18);
        vault.deposit(address(token1), 10_000e18);
        vm.stopPrank();
        vault.openBand(-600, 600, 1_000e18, 1_000e18);

        // Fund the swapper who generates the fees both sides will split.
        // MockERC20's transferFrom doesn't enforce allowance (see
        // test/PairVault.t.sol), so no approve() call is needed for
        // V3TestRouter to pull from the swapper's balance.
        token0.mint(swapper, 1_000e18);
        token1.mint(swapper, 1_000e18);
    }

    function _swap(bool zeroForOne, int256 amountSpecified) internal {
        uint160 limit = zeroForOne ? TickMath.MIN_SQRT_RATIO + 1 : TickMath.MAX_SQRT_RATIO - 1;
        vm.prank(swapper);
        router.swap(pool, swapper, zeroForOne, amountSpecified, limit);
    }

    function test_collectFees_pullsRealFeesFromARealSwap() public {
        uint256 tvlABefore = vault.tvlA();
        uint256 tvlBBefore = vault.tvlB();
        uint256 vaultToken0Before = token0.balanceOf(address(vault));

        _swap(true, -100e18); // sell 100 token0 into the pool -> vault's liquidity earns token0-side fees

        (uint256 amount0, uint256 amount1) = vault.collectFees();

        assertGt(amount0, 0, "swapping token0 in should generate token0-denominated fees for in-range liquidity");
        assertEq(vault.tvlA(), tvlABefore + amount0, "collected fees must flow into tvlA (NAV)");
        assertEq(vault.tvlB(), tvlBBefore + amount1);
        assertEq(token0.balanceOf(address(vault)), vaultToken0Before + amount0, "real tokens must land in the vault");
    }

    /// @notice The 80/15/5 split (PairVault.PROTOCOL_BPS/KEEPER_BPS/TREASURY_BPS)
    ///         against a real harvested amount, called by a third-party keeper
    ///         address distinct from the depositor and the treasury, so a bug
    ///         crediting the wrong party would actually be caught here.
    function test_collectFees_splitsFeesBetweenDepositorsTreasuryAndKeeper() public {
        uint256 treasury0Before = token0.balanceOf(treasury);
        uint256 keeper0Before = token0.balanceOf(keeper);
        uint256 tvlABefore = vault.tvlA();

        _swap(true, -100e18);

        vm.prank(keeper);
        (uint256 depositorAmount0,) = vault.collectFees();

        uint256 treasuryGain = token0.balanceOf(treasury) - treasury0Before;
        uint256 keeperGain = token0.balanceOf(keeper) - keeper0Before;
        uint256 rawFee = depositorAmount0 + treasuryGain + keeperGain;

        assertGt(rawFee, 0, "the swap must have generated a real fee to split");
        assertEq(vault.tvlA(), tvlABefore + depositorAmount0, "only the depositor's net share enters NAV");
        assertEq(treasuryGain, (rawFee * vault.TREASURY_BPS()) / 10_000, "treasury must get exactly TREASURY_BPS");
        assertEq(keeperGain, (rawFee * vault.KEEPER_BPS()) / 10_000, "the calling keeper must get exactly KEEPER_BPS");
        assertEq(
            depositorAmount0,
            rawFee - treasuryGain - keeperGain,
            "depositors get whatever's left after treasury + keeper, not a separately-rounded 80%"
        );
    }

    function test_collectFees_splitsProportionallyBetweenTwoOwners_automatically() public {
        // A second, independent LP adds EQUAL liquidity in the identical range
        // under a different owner (itself, since it calls mint directly).
        address lp = _addOutsideLp();

        _swap(true, -100e18);

        (uint256 vaultAmount0,) = vault.collectFees();

        // The outside LP's own liquidity should be roughly equal to the
        // vault's, since both were funded with the same amounts in the same
        // range — confirms the setup is genuinely ~50/50, not lopsided.
        uint128 lpLiquidity = _positionLiquidity(lp, -600, 600);
        uint128 vaultLiquidity = _positionLiquidity(address(vault), -600, 600);
        assertApproxEqRel(lpLiquidity, vaultLiquidity, 0.05e18);
        assertGt(vaultAmount0, 0);
    }

    function _positionLiquidity(address owner, int24 tickLower, int24 tickUpper) internal view returns (uint128 liquidity) {
        bytes32 key = keccak256(abi.encodePacked(owner, tickLower, tickUpper));
        (liquidity,,,,) = pool.positions(key);
    }

    function _addOutsideLp() internal returns (address lpAddress) {
        // A minimal stand-in "outside LP": mints roughly the same liquidity
        // the vault has, in the identical range, under its own address.
        PoolMintTestLike lp = new PoolMintTestLike(pool);
        token0.mint(address(lp), 1_000e18);
        token1.mint(address(lp), 1_000e18);
        lp.addLiquidity(-600, 600, 1_000e18, 1_000e18);
        return address(lp);
    }
}

/// @dev Minimal "outside LP" — mints as itself (a genuinely different owner
///      from the vault), paying whatever the pool says is owed out of its own
///      balance, using the exact same LiquidityMath conversion PairVault.
///      openBand uses.
contract PoolMintTestLike is IUniswapV3MintCallback {
    IUniswapV3Pool immutable pool;

    constructor(IUniswapV3Pool _pool) {
        pool = _pool;
    }

    function addLiquidity(int24 tickLower, int24 tickUpper, uint256 amount0, uint256 amount1) external {
        (uint160 sqrtPriceX96,,,,,,) = pool.slot0();
        uint160 sqrtPa = TickMath.getSqrtRatioAtTick(tickLower);
        uint160 sqrtPb = TickMath.getSqrtRatioAtTick(tickUpper);
        uint128 liquidity = LiquidityMath.getLiquidityForAmounts(sqrtPriceX96, sqrtPa, sqrtPb, amount0, amount1);
        pool.mint(address(this), tickLower, tickUpper, liquidity, "");
    }

    function uniswapV3MintCallback(uint256 amount0Owed, uint256 amount1Owed, bytes calldata) external {
        require(msg.sender == address(pool));
        if (amount0Owed > 0) {
            (bool ok,) = pool.token0().call(abi.encodeWithSignature("transfer(address,uint256)", msg.sender, amount0Owed));
            require(ok, "pay token0 failed");
        }
        if (amount1Owed > 0) {
            (bool ok,) = pool.token1().call(abi.encodeWithSignature("transfer(address,uint256)", msg.sender, amount1Owed));
            require(ok, "pay token1 failed");
        }
    }
}
